/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JList;
import javax.swing.JOptionPane;
import model.server.TCPServer;
import model.server.TCPUser;
import model.User;
import org.json.JSONException;
import org.json.JSONObject;
import pojoutils.ReceptionsPojo;
import thread.utils.TCPServerThread;
import utils.ConsoleDate;

/**
 *
 * @author gilson
 */
public class ClientView extends javax.swing.JFrame {

    private TCPUser tCPUser;
    private boolean loggedUser = false;
    private User user;
    private boolean homeOperation;
    
    /**
     * Creates new form Client
     */
    public ClientView() {
        this.homeOperation = true;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        serverconnection = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        serverconnectionbtn = new javax.swing.JButton();
        serverconnectionip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        serverconnectionport = new javax.swing.JTextField();
        signuppanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        signupname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        signupphone = new javax.swing.JTextField();
        signupcpf = new javax.swing.JTextField();
        signuppassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        loginpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginbtn = new javax.swing.JButton();
        logincpf = new javax.swing.JTextField();
        loginpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signupbtn_link = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        homepanel = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();
        updateUserbtn = new javax.swing.JButton();
        donateListbtn = new javax.swing.JButton();
        receiveListbtn = new javax.swing.JButton();
        receiveOrDonatebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        receiveOrDonateList = new javax.swing.JList();
        updateUserpanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        updatename = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        updatephone = new javax.swing.JTextField();
        updatecpf = new javax.swing.JTextField();
        updatepassword = new javax.swing.JPasswordField();
        updatecancelbtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        createdonationpanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        createdonationquantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        createdonationbtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        createdonationmeasure = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        createdonationdescription = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Server connection");

        serverconnectionbtn.setBackground(new java.awt.Color(102, 187, 106));
        serverconnectionbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        serverconnectionbtn.setForeground(new java.awt.Color(255, 255, 255));
        serverconnectionbtn.setText("Connect");
        serverconnectionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverconnectionbtnActionPerformed(evt);
            }
        });

        serverconnectionip.setToolTipText("User");
        serverconnectionip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverconnectionipActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel10.setText("IP Address");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel11.setText("Port");

        serverconnectionport.setToolTipText("User");
        serverconnectionport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverconnectionportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 211, Short.MAX_VALUE)
                        .addComponent(serverconnectionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serverconnectionip)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addComponent(serverconnectionport))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverconnectionip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverconnectionport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(serverconnectionbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout serverconnectionLayout = new javax.swing.GroupLayout(serverconnection);
        serverconnection.setLayout(serverconnectionLayout);
        serverconnectionLayout.setHorizontalGroup(
            serverconnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverconnectionLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(serverconnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        serverconnectionLayout.setVerticalGroup(
            serverconnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, serverconnectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(serverconnection, "card5");

        signupname.setToolTipText("User");
        signupname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel6.setText("Phone");

        signupbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(66, 165, 245));
        signupbtn.setText("Signup");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel7.setText("CPF");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel8.setText("Password");

        signupphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupphoneActionPerformed(evt);
            }
        });

        signupcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupcpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupname)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 211, Short.MAX_VALUE)
                                .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addComponent(signupphone)
                            .addComponent(signupcpf)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(signuppassword))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signuppassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Signup");

        javax.swing.GroupLayout signuppanelLayout = new javax.swing.GroupLayout(signuppanel);
        signuppanel.setLayout(signuppanelLayout);
        signuppanelLayout.setHorizontalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        signuppanelLayout.setVerticalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(signuppanel, "card2");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        loginbtn.setBackground(new java.awt.Color(66, 165, 245));
        loginbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        logincpf.setToolTipText("User");
        logincpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logincpfActionPerformed(evt);
            }
        });

        loginpassword.setToolTipText("Password");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel2.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel3.setText("Password");

        signupbtn_link.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        signupbtn_link.setForeground(new java.awt.Color(66, 165, 245));
        signupbtn_link.setText("Signup");
        signupbtn_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtn_linkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(signupbtn_link, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginpassword)
                    .addComponent(logincpf)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logincpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupbtn_link, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        getContentPane().add(loginpanel, "card3");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Home");

        logoutbtn.setBackground(new java.awt.Color(244, 67, 54));
        logoutbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        updateUserbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        updateUserbtn.setForeground(new java.awt.Color(66, 165, 245));
        updateUserbtn.setText("Edit account");
        updateUserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserbtnActionPerformed(evt);
            }
        });

        donateListbtn.setText("Donate");
        donateListbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateListbtnActionPerformed(evt);
            }
        });

        receiveListbtn.setText("Receive");
        receiveListbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveListbtnActionPerformed(evt);
            }
        });

        receiveOrDonatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveOrDonatebtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(receiveOrDonateList);

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateUserbtn)
                        .addGap(20, 20, 20)
                        .addComponent(logoutbtn))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addComponent(donateListbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receiveOrDonatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(receiveListbtn)))
                .addContainerGap())
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(logoutbtn)
                    .addComponent(updateUserbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(donateListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(receiveListbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiveOrDonatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(homepanel, "card4");

        updatename.setToolTipText("User");
        updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel12.setText("Name");

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel14.setText("Phone");

        updatebtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(66, 165, 245));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel15.setText("CPF");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel16.setText("Password");

        updatephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatephoneActionPerformed(evt);
            }
        });

        updatecpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecpfActionPerformed(evt);
            }
        });

        updatecancelbtn.setBackground(new java.awt.Color(244, 67, 54));
        updatecancelbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        updatecancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatecancelbtn.setText("Cancel");
        updatecancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatename)
                            .addComponent(jSeparator4)
                            .addComponent(updatephone)
                            .addComponent(updatecpf)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(updatepassword)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(updatecancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatecpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatepassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Edit account");

        javax.swing.GroupLayout updateUserpanelLayout = new javax.swing.GroupLayout(updateUserpanel);
        updateUserpanel.setLayout(updateUserpanelLayout);
        updateUserpanelLayout.setHorizontalGroup(
            updateUserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateUserpanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateUserpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        updateUserpanelLayout.setVerticalGroup(
            updateUserpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateUserpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(updateUserpanel, "card2");

        createdonationquantity.setToolTipText("User");
        createdonationquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdonationquantityActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel18.setText("Quantity");

        jLabel19.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel19.setText("Measure unit");

        createdonationbtn.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        createdonationbtn.setForeground(new java.awt.Color(66, 165, 245));
        createdonationbtn.setText("Create");
        createdonationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdonationbtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel20.setText("Description");

        createdonationmeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createdonationmeasureActionPerformed(evt);
            }
        });

        createdonationdescription.setColumns(20);
        createdonationdescription.setRows(5);
        jScrollPane1.setViewportView(createdonationdescription);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(createdonationquantity)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 211, Short.MAX_VALUE)
                                .addComponent(createdonationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5)
                            .addComponent(createdonationmeasure)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(0, 234, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createdonationquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createdonationmeasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(createdonationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel22.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Create donation");

        javax.swing.GroupLayout createdonationpanelLayout = new javax.swing.GroupLayout(createdonationpanel);
        createdonationpanel.setLayout(createdonationpanelLayout);
        createdonationpanelLayout.setHorizontalGroup(
            createdonationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdonationpanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createdonationpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        createdonationpanelLayout.setVerticalGroup(
            createdonationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createdonationpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(createdonationpanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serverconnectionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverconnectionbtnActionPerformed
        if(!this.serverconnectionip.getText().equals("")&&
            !this.serverconnectionport.getText().equals("")){
            try{
                this.tCPUser = new TCPUser(this);
                this.tCPUser.connect(this.serverconnectionip.getText(),
                                Integer.valueOf(this.serverconnectionport.getText()));
                this.serverconnection.setVisible(false);
                this.loginpanel.setVisible(true);
            }catch(IOException e){
                System.out.println(ConsoleDate.getConsoleDate()+"Connection error");
            }
        }
        
    }//GEN-LAST:event_serverconnectionbtnActionPerformed

    private void serverconnectionipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverconnectionipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverconnectionipActionPerformed
    
    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        JSONObject jsonobj = new JSONObject();
        JSONObject data = new JSONObject();
        try {
            if(!this.logincpf.getText().isEmpty()&&
               !(this.loginpassword.getPassword().length == 0)){
                data.put("cpf", this.logincpf.getText());
                data.put("password", new String(this.loginpassword.getPassword()));
                jsonobj.put("login", data);
                this.tCPUser.sendMessage(jsonobj);
            }else{
                if(this.logincpf.getText().isEmpty()){
                    this.logincpf.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.loginpassword.getPassword().length == 0){
                    this.loginpassword.setBorder(BorderFactory.createLineBorder(Color.red));
                }
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_loginbtnActionPerformed

    private void logincpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logincpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logincpfActionPerformed

    private void signupbtn_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtn_linkActionPerformed
        // TODO add your handling code here:
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(true);
    }//GEN-LAST:event_signupbtn_linkActionPerformed

    private void signupnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupnameActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        // TODO add your handling code here:
        
        JSONObject jsonobj = new JSONObject();
        JSONObject data = new JSONObject();
        try {
            if(!this.signupphone.getText().isEmpty()&&
               !this.signupcpf.getText().isEmpty()&&
               !this.signupname.getText().isEmpty()&&
               !(this.signuppassword.getPassword().length == 0)){
                data.put("name", this.signupname.getText());
                data.put("cpf", this.signupcpf.getText());
                data.put("phone", this.signupphone.getText());
                data.put("password", new String(this.signuppassword.getPassword()));
                jsonobj.put("register", data);
                this.tCPUser.sendMessage(jsonobj);
            }else{
                if(this.signupcpf.getText().isEmpty()){
                    this.signupcpf.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.signupname.getText().isEmpty()){
                    this.signupname.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.signupphone.getText().isEmpty()){
                    this.signupphone.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.signuppassword.getPassword().length == 0){
                    this.signuppassword.setBorder(BorderFactory.createLineBorder(Color.red));
                }
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //show error window
            System.out.println(ConsoleDate.getConsoleDate()+"User already registered");
        }
    }//GEN-LAST:event_signupbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        JSONObject jsonobj = new JSONObject();
        try{
            jsonobj.put("close", new JSONObject());
            this.tCPUser.sendMessage(jsonobj);
        }catch(JSONException | IOException e){
            e.printStackTrace();
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void signupcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupcpfActionPerformed

    private void signupphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupphoneActionPerformed

    private void serverconnectionportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverconnectionportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serverconnectionportActionPerformed

    private void updateUserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserbtnActionPerformed
        // TODO add your handling code here:
        this.homepanel.setVisible(false);
        this.updateUserpanel.setVisible(true);
    }//GEN-LAST:event_updateUserbtnActionPerformed

    private void updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatenameActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        JSONObject jsonobj = new JSONObject();
        JSONObject data = new JSONObject();
        try {
            if(!this.updatephone.getText().isEmpty()&&
               !this.updatecpf.getText().isEmpty()&&
               !this.updatename.getText().isEmpty()&&
               !(this.updatepassword.getPassword().length == 0)){
                data.put("id", this.user.getId());
                data.put("name", this.updatename.getText());
                data.put("cpf", this.updatecpf.getText());
                data.put("phone", this.updatephone.getText());
                data.put("password", new String(this.updatepassword.getPassword()));
                jsonobj.put("userUpdate", data);
                this.tCPUser.sendMessage(jsonobj);
            }else{
                if(this.updatecpf.getText().isEmpty()){
                    this.updatecpf.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.updatename.getText().isEmpty()){
                    this.updatename.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.updatephone.getText().isEmpty()){
                    this.updatephone.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.updatepassword.getPassword().length == 0){
                    this.updatepassword.setBorder(BorderFactory.createLineBorder(Color.red));
                }
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updatebtnActionPerformed

    private void updatephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatephoneActionPerformed

    private void updatecpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatecpfActionPerformed

    private void updatecancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecancelbtnActionPerformed
        // TODO add your handling code here:
        this.updateUserpanel.setVisible(false);
        this.homepanel.setVisible(true);
    }//GEN-LAST:event_updatecancelbtnActionPerformed

    private void createdonationquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdonationquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createdonationquantityActionPerformed

    private void createdonationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdonationbtnActionPerformed
        // TODO add your handling code here:
        JSONObject jsonobj = new JSONObject();
        JSONObject data = new JSONObject();
        try {
            if(!this.createdonationquantity.getText().isEmpty()&&
               !this.createdonationmeasure.getText().isEmpty()){
                data.put("quantity", this.createdonationquantity.getText());
                data.put("measureUnit", this.createdonationmeasure.getText());
                data.put("description", this.createdonationdescription.getText());
                data.put("idDonor", this.user.getId());
                jsonobj.put("donation", data);
                this.tCPUser.sendMessage(jsonobj);
            }else{
                if(this.createdonationquantity.getText().isEmpty()){
                    this.createdonationquantity.setBorder(BorderFactory.createLineBorder(Color.red));
                }
                if(this.createdonationmeasure.getText().isEmpty()){
                    this.createdonationmeasure.setBorder(BorderFactory.createLineBorder(Color.red));
                }
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(ClientView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createdonationbtnActionPerformed

    private void createdonationmeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createdonationmeasureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createdonationmeasureActionPerformed

    private void donateListbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateListbtnActionPerformed
        // TODO add your handling code here:
        this.receiveOrDonatebtn.setText("Create Donation");
        this.homeOperation = true;
    }//GEN-LAST:event_donateListbtnActionPerformed

    private void receiveListbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveListbtnActionPerformed
        // TODO add your handling code here:
        this.receiveOrDonatebtn.setText("Receive");
        this.homeOperation = false;
        try{
            JSONObject jsonobj = new JSONObject();
            jsonobj.put("receptions", new JSONObject());
            this.tCPUser.sendMessage(jsonobj);
        }catch(JSONException | IOException ex){
            System.out.println(ConsoleDate.getConsoleDate()+"Receptions server fetch error");
        }
    }//GEN-LAST:event_receiveListbtnActionPerformed

    private void receiveOrDonatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveOrDonatebtnActionPerformed
        //Create donation
        if(homeOperation){
            this.homepanel.setVisible(false);
            this.createdonationpanel.setVisible(true);
        }else{//Receive donation
              
        }
    }//GEN-LAST:event_receiveOrDonatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createdonationbtn;
    private javax.swing.JTextArea createdonationdescription;
    private javax.swing.JTextField createdonationmeasure;
    private javax.swing.JPanel createdonationpanel;
    private javax.swing.JTextField createdonationquantity;
    private javax.swing.JButton donateListbtn;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField logincpf;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPasswordField loginpassword;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton receiveListbtn;
    private javax.swing.JList receiveOrDonateList;
    private javax.swing.JButton receiveOrDonatebtn;
    private javax.swing.JPanel serverconnection;
    private javax.swing.JButton serverconnectionbtn;
    private javax.swing.JTextField serverconnectionip;
    private javax.swing.JTextField serverconnectionport;
    private javax.swing.JButton signupbtn;
    private javax.swing.JButton signupbtn_link;
    private javax.swing.JTextField signupcpf;
    private javax.swing.JTextField signupname;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JPasswordField signuppassword;
    private javax.swing.JTextField signupphone;
    private javax.swing.JButton updateUserbtn;
    private javax.swing.JPanel updateUserpanel;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton updatecancelbtn;
    private javax.swing.JTextField updatecpf;
    private javax.swing.JTextField updatename;
    private javax.swing.JPasswordField updatepassword;
    private javax.swing.JTextField updatephone;
    // End of variables declaration//GEN-END:variables

    public void setLoggedUser(boolean state){
        this.loggedUser = state;
    }
    
    public void setHomepanelVisibility(boolean state) {
        this.serverconnection.setVisible(false);
        this.homepanel.setVisible(state);
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(false);
    }

    public void setLoginpanelVisibility(boolean state) {
        this.serverconnection.setVisible(false);
        this.homepanel.setVisible(false);
        this.loginpanel.setVisible(state);
        this.signuppanel.setVisible(false);
    }

    public void setSignuppanelVisibility(boolean state) {
        this.serverconnection.setVisible(false);
        this.homepanel.setVisible(false);
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(state);
    }
    
    public void setServerconnectionVisibility(boolean state){
        this.updateUserpanel.setVisible(false);
        this.serverconnection.setVisible(false);
        this.createdonationpanel.setVisible(false);
        this.homepanel.setVisible(false);
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(false);
        this.serverconnection.setVisible(true);
    }
    
    public void setUpdateUserVisibility(boolean state){
        this.updateUserpanel.setVisible(false);
        this.serverconnection.setVisible(false);
        this.homepanel.setVisible(true);
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(false);
    }
    
    public void setCreateDonationVisibility(boolean state){
        this.updateUserpanel.setVisible(false);
        this.serverconnection.setVisible(false);
        this.createdonationpanel.setVisible(false);
        this.homepanel.setVisible(true);
        this.loginpanel.setVisible(false);
        this.signuppanel.setVisible(false);
    }
    
    public void setUser(User user){
        this.user = user;
    }
    
    public void setReceiveOrDonateList(JList jList){
        this.receiveOrDonateList = jList;
    }
    
    public JList getReceiveOrDonateList(){
        return this.receiveOrDonateList;
    }
}
